# -*- coding: utf-8 -*-
"""ML-OPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11IGHlB0q7UTNeng3yc0dTnYgev9yffTe
"""

import pandas as pd
import numpy as np
import random

# Make results reproducible
np.random.seed(42)
random.seed(42)

# Number of students
n = 500

# Student IDs
student_ids = range(1001, 1001 + n)

# Generate data
age = np.random.randint(20, 25, n)
gender = np.random.choice(['Male', 'Female'], n)

cgpa = np.round(np.random.uniform(5.5, 10.0, n), 2)
attendance = np.random.randint(60, 101, n)

programming = np.random.randint(40, 101, n)
dsa = np.random.randint(40, 101, n)
algorithms = np.random.randint(40, 101, n)
dbms = np.random.randint(40, 101, n)
os = np.random.randint(40, 101, n)
cn = np.random.randint(40, 101, n)
oop = np.random.randint(40, 101, n)
python = np.random.randint(40, 101, n)
java = np.random.randint(40, 101, n)
sql = np.random.randint(40, 101, n)
web = np.random.randint(40, 101, n)
git = np.random.randint(30, 101, n)
cloud = np.random.randint(30, 101, n)
aiml = np.random.randint(30, 101, n)

communication = np.random.randint(40, 101, n)
problem_solving = np.random.randint(40, 101, n)
teamwork = np.random.randint(40, 101, n)

internship = np.random.choice([0, 1], n, p=[0.4, 0.6])

projects = np.random.randint(1, 6, n)
certifications = np.random.randint(0, 6, n)

aptitude = np.random.randint(40, 101, n)

# Calculate Average Skill
average_skill = np.round(
    (
        programming + dsa + algorithms + dbms + os + cn +
        oop + python + java + sql + web + git +
        cloud + aiml + communication +
        problem_solving + teamwork
    ) / 17,
    2
)

# Industry required skill
industry_requirement = np.random.randint(75, 91, n)

# Skill Gap
skill_gap = np.round(industry_requirement - average_skill, 2)

# Employability Decision
employability = []

for i in range(n):
    if (
        cgpa[i] >= 7.0 and
        communication[i] >= 65 and
        problem_solving[i] >= 70 and
        skill_gap[i] <= 10 and
        (internship[i] == 1 or projects[i] >= 3)
    ):
        employability.append("Yes")
    else:
        employability.append("No")


df = pd.DataFrame({
    "Student_ID": student_ids,
    "Age": age,
    "Gender": gender,
    "CGPA": cgpa,
    "Attendance": attendance,
    "Programming": programming,
    "Data_Structures": dsa,
    "Algorithms": algorithms,
    "DBMS": dbms,
    "Operating_Systems": os,
    "Computer_Networks": cn,
    "OOP": oop,
    "Python": python,
    "Java": java,
    "SQL": sql,
    "Web_Development": web,
    "Git_GitHub": git,
    "Cloud_Computing": cloud,
    "AI_ML": aiml,
    "Communication": communication,
    "Problem_Solving": problem_solving,
    "Teamwork": teamwork,
    "Internship": internship,
    "Projects": projects,
    "Certifications": certifications,
    "Aptitude": aptitude,
    "Average_Skill": average_skill,
    "Industry_Requirement": industry_requirement,
    "Skill_Gap": skill_gap,
    "Employability": employability
})


df.to_csv("synthetic_employability_dataset.csv", index=False)

print(df.head(10))

print("\nDataset Shape:", df.shape)
print("\nEmployability Count:")
print(df["Employability"].value_counts())

print(df.shape)

import os

print(os.listdir())

from google.colab import files

files.download("synthetic_employability_dataset.csv")

# ===============================
# DATA PREPROCESSING
# ===============================

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load Dataset
df = pd.read_csv("synthetic_employability_dataset.csv")

print("="*50)
print("First 5 Rows")
print("="*50)
print(df.head())

print("\n" + "="*50)
print("Dataset Shape")
print("="*50)
print(df.shape)

print("\n" + "="*50)
print("Dataset Information")
print("="*50)
print(df.info())

print("\n" + "="*50)
print("Statistical Summary")
print("="*50)
print(df.describe())

# -------------------------------
# Missing Values
# -------------------------------
print("\n" + "="*50)
print("Missing Values")
print("="*50)
print(df.isnull().sum())

# -------------------------------
# Duplicate Records
# -------------------------------
print("\n" + "="*50)
print("Duplicate Rows")
print("="*50)
duplicates = df.duplicated().sum()
print("Duplicate Rows:", duplicates)

if duplicates > 0:
    df = df.drop_duplicates()
    print("Duplicates Removed Successfully")
else:
    print("No Duplicate Rows Found")

# -------------------------------
# Data Types
# -------------------------------
print("\n" + "="*50)
print("Data Types")
print("="*50)
print(df.dtypes)

# -------------------------------
# Encode Categorical Variables
# -------------------------------
df["Gender"] = df["Gender"].map({
    "Male":0,
    "Female":1
})

df["Employability"] = df["Employability"].map({
    "No":0,
    "Yes":1
})

print("\nCategorical Variables Encoded Successfully.")

# -------------------------------
# Verify Encoded Data
# -------------------------------
print("\n" + "="*50)
print("First 5 Rows After Encoding")
print("="*50)
print(df.head())

# -------------------------------
# Class Distribution
# -------------------------------
print("\n" + "="*50)
print("Employability Class Distribution")
print("="*50)
print(df["Employability"].value_counts())

print("\nPercentage Distribution")
print(df["Employability"].value_counts(normalize=True)*100)

# -------------------------------
# Check Dataset Balance
# -------------------------------
counts = df["Employability"].value_counts()

ratio = counts.max()/counts.min()

print("\nBalance Ratio :", round(ratio,2))

if ratio < 1.5:
    print("Dataset is BALANCED")
else:
    print("Dataset is IMBALANCED")

# -------------------------------
# Class Distribution Plot
# -------------------------------
plt.figure(figsize=(6,4))
df["Employability"].value_counts().plot(kind="bar")

plt.title("Employability Class Distribution")
plt.xlabel("Employability (0 = No, 1 = Yes)")
plt.ylabel("Number of Students")
plt.xticks(rotation=0)
plt.show()

# -------------------------------
# Save Preprocessed Dataset
# -------------------------------
df.to_csv("preprocessed_employability_dataset.csv", index=False)

print("\nPreprocessed Dataset Saved Successfully.")

print(df["Employability"].value_counts())

import pandas as pd
import numpy as np
import random

# -----------------------------
# Set Random Seed
# -----------------------------
np.random.seed(42)
random.seed(42)

# -----------------------------
# Number of Students
# -----------------------------
n = 500

# -----------------------------
# Generate Student Data
# -----------------------------
student_ids = range(1001, 1001 + n)

age = np.random.randint(20, 25, n)
gender = np.random.choice(['Male', 'Female'], n)

cgpa = np.round(np.random.uniform(5.5, 10.0, n), 2)
attendance = np.random.randint(60, 101, n)

programming = np.random.randint(40, 101, n)
dsa = np.random.randint(40, 101, n)
algorithms = np.random.randint(40, 101, n)
dbms = np.random.randint(40, 101, n)
os = np.random.randint(40, 101, n)
cn = np.random.randint(40, 101, n)
oop = np.random.randint(40, 101, n)
python = np.random.randint(40, 101, n)
java = np.random.randint(40, 101, n)
sql = np.random.randint(40, 101, n)
web = np.random.randint(40, 101, n)

git = np.random.randint(30, 101, n)
cloud = np.random.randint(30, 101, n)
aiml = np.random.randint(30, 101, n)

communication = np.random.randint(40, 101, n)
problem_solving = np.random.randint(40, 101, n)
teamwork = np.random.randint(40, 101, n)

internship = np.random.choice([0,1], n, p=[0.4,0.6])

projects = np.random.randint(1,6,n)

certifications = np.random.randint(0,6,n)

aptitude = np.random.randint(40,101,n)

# -----------------------------
# Average Skill
# -----------------------------
average_skill = np.round(
(
programming+dsa+algorithms+dbms+os+cn+
oop+python+java+sql+web+git+
cloud+aiml+communication+
problem_solving+teamwork
)/17,2)

# -----------------------------
# Industry Requirement
# -----------------------------
industry_requirement = np.random.randint(75,91,n)

# -----------------------------
# Skill Gap
# -----------------------------
skill_gap = np.round(industry_requirement-average_skill,2)

# -----------------------------
# Balanced Employability
# -----------------------------
employability=[]

for i in range(n):

    score=0

    if cgpa[i]>=7:
        score+=1

    if average_skill[i]>=70:
        score+=1

    if communication[i]>=60:
        score+=1

    if problem_solving[i]>=60:
        score+=1

    if internship[i]==1:
        score+=1

    if projects[i]>=3:
        score+=1

    if certifications[i]>=2:
        score+=1

    if aptitude[i]>=60:
        score+=1

    if skill_gap[i]<=12:
        score+=1

    if score>=5:
        employability.append("Yes")
    else:
        employability.append("No")

# -----------------------------
# Create DataFrame
# -----------------------------
df=pd.DataFrame({

"Student_ID":student_ids,
"Age":age,
"Gender":gender,
"CGPA":cgpa,
"Attendance":attendance,

"Programming":programming,
"Data_Structures":dsa,
"Algorithms":algorithms,
"DBMS":dbms,
"Operating_Systems":os,
"Computer_Networks":cn,
"OOP":oop,

"Python":python,
"Java":java,
"SQL":sql,
"Web_Development":web,

"Git_GitHub":git,
"Cloud_Computing":cloud,
"AI_ML":aiml,

"Communication":communication,
"Problem_Solving":problem_solving,
"Teamwork":teamwork,

"Internship":internship,
"Projects":projects,
"Certifications":certifications,
"Aptitude":aptitude,

"Average_Skill":average_skill,
"Industry_Requirement":industry_requirement,
"Skill_Gap":skill_gap,

"Employability":employability

})

# -----------------------------
# Save Dataset
# -----------------------------
df.to_csv("synthetic_employability_dataset.csv",index=False)

# -----------------------------
# Display Output
# -----------------------------
print(df.head())

print("\nDataset Shape")
print(df.shape)

print("\nEmployability Distribution")
print(df["Employability"].value_counts())

print("\nPercentage")
print(df["Employability"].value_counts(normalize=True)*100)

df["Employability"].unique()

# Convert Employability to numeric

df["Employability"] = df["Employability"].map({
    "No": 0,
    "Yes": 1
})

# Verify
print(df["Employability"].unique())

!pip install imbalanced-learn

print(df["Gender"].unique())

df["Gender"] = df["Gender"].map({
    "Male": 0,
    "Female": 1
})

# Verify
print(df["Gender"].unique())

from imblearn.over_sampling import SMOTE
from collections import Counter

# Separate features and target
X = df.drop("Employability", axis=1)
y = df["Employability"]

# Apply SMOTE
smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

# Check class distribution
print("Before SMOTE:", Counter(y))
print("After SMOTE:", Counter(y_resampled))

import pandas as pd

# Create balanced DataFrame
balanced_df = pd.DataFrame(X_resampled, columns=X.columns)

# Add target column
balanced_df["Employability"] = y_resampled

# Save dataset
balanced_df.to_csv("balanced_employability_dataset.csv", index=False)

print("Balanced dataset saved successfully!")

print("\nShape of Balanced Dataset:")
print(balanced_df.shape)

print("\nClass Distribution:")
print(balanced_df["Employability"].value_counts())

from google.colab import files

files.download("balanced_employability_dataset.csv")

# ==============================
# Decision Tree Classification
# ==============================

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# -----------------------------
# Features and Target
# -----------------------------
X = balanced_df.drop("Employability", axis=1)
y = balanced_df["Employability"]

# -----------------------------
# Train-Test Split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Data Shape :", X_train.shape)
print("Testing Data Shape  :", X_test.shape)

# -----------------------------
# Train Decision Tree
# -----------------------------
model = DecisionTreeClassifier(random_state=42)

model.fit(X_train, y_train)

# -----------------------------
# Prediction
# -----------------------------
y_pred = model.predict(X_test)

# -----------------------------
# Accuracy
# -----------------------------
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy :", round(accuracy*100,2), "%")

# -----------------------------
# Confusion Matrix
# -----------------------------
print("\nConfusion Matrix")

cm = confusion_matrix(y_test, y_pred)

print(cm)

# -----------------------------
# Classification Report
# -----------------------------
print("\nClassification Report")

print(classification_report(y_test, y_pred))

import pandas as pd
import matplotlib.pyplot as plt

# Feature Importance
importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(by='Importance', ascending=False)

print(importance)

# Plot
plt.figure(figsize=(10,6))
plt.barh(importance['Feature'], importance['Importance'])
plt.title("Feature Importance")
plt.xlabel("Importance Score")
plt.gca().invert_yaxis()
plt.show()

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

ConfusionMatrixDisplay.from_estimator(model, X_test, y_test)

plt.title("Confusion Matrix")
plt.show()